# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: ['bower_components','node_modules']

# Site settings
title: Underskeleton
description: > # this means to ignore newlines until "baseurl:"
  Underscores ( _s ) + Skeleton Boilerplate = Fast to load with a minimalist
  css grid for your next WordPress Theme.
  Underskeleton is a starter theme with minimalist, dead simple css 
  grid system and just enough styling to get starter with your next 
  awesome WordPress theme.
  It got most of the _s PHP and JS files + Skeleton styles and grid system.
baseurl: "/underskeleton" # the subpath of your site, e.g. /blog 
url: "http://dvlopes.github.io" # the base hostname & protocol for your site

source_version: "v0.1.1"

# Build settings
markdown: kramdown
